# Generated by Django 4.1 on 2022-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='header_image',
            field=models.ImageField(null=True, upload_to='server/'),
        ),
        migrations.AlterField(
            model_name='server',
            name='logo',
            field=models.ImageField(upload_to='server/'),
        ),
    ]
